#!/bin/bash

sudo ip netns add 'H1'
sudo ip netns add 'H2'
sudo ip netns add 'H3'
sudo ip netns add 'R'

sudo ip link add 'veth1' type veth peer name 'veth2'
sudo ip link add 'veth4' type veth peer name 'veth5'
sudo ip link add 'veth3' type veth peer name 'veth6'

sudo ip link set 'veth1' netns 'H1'
sudo ip link set 'veth2' netns 'R'
sudo ip link set 'veth3' netns 'R'
sudo ip link set 'veth4' netns 'R'
sudo ip link set 'veth5' netns 'H3'
sudo ip link set 'veth6' netns 'H2'

sudo ip netns exec 'H1' ip addr add 10.0.10.36/24 dev veth1
sudo ip netns exec 'R' ip addr add 10.0.10.1/24 dev veth2
sudo ip netns exec 'R' ip addr add 10.0.20.1/24 dev veth3
sudo ip netns exec 'R' ip addr add 10.0.30.1/24 dev veth4
sudo ip netns exec 'H3' ip addr add 10.0.30.36/24 dev veth5
sudo ip netns exec 'H2' ip addr add 10.0.20.36/24 dev veth6

sudo ip netns exec 'R' brctl addbr br0

sudo ip netns exec 'R' brctl addif br0 veth2
sudo ip netns exec 'R' brctl addif br0 veth3
sudo ip netns exec 'R' brctl addif br0 veth4

sudo ip netns exec 'H1' ip link set dev veth1 up
sudo ip netns exec 'R' ip link set dev veth2 up
sudo ip netns exec 'R' ip link set dev veth3 up
sudo ip netns exec 'R' ip link set dev veth4 up
sudo ip netns exec 'H3' ip link set dev veth5 up
sudo ip netns exec 'H2' ip link set dev veth6 up

sudo ip netns exec 'R' ip link set dev br0 up

sudo ip netns exec 'R' sysctl net.ipv4.ip_forward=1
